// <auto-generated />
using System;
using System.Collections.Generic;
using Chipseky.MamkinInvestor.Domain;
using Chipseky.MamkinInvestor.WebApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chipseky.MamkinInvestor.WebApi.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240615161711_AddTradeUpdatedAt")]
    partial class AddTradeUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chipseky.MamkinInvestor.Domain.Trade", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentProfit")
                        .HasColumnType("numeric")
                        .HasColumnName("current_profit");

                    b.Property<decimal>("HeldCoinsCount")
                        .HasColumnType("numeric")
                        .HasColumnName("held_coins_count");

                    b.Property<IEnumerable<TradeOrder>>("History")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("history");

                    b.Property<string>("TradingPair")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trading_pair");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TradeId")
                        .HasName("pk_trades");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Chipseky.MamkinInvestor.WebApi.Infrastructure.Database.DbTradeEvent", b =>
                {
                    b.Property<long>("DbTradeEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("db_trade_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DbTradeEventId"));

                    b.Property<object>("Data")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("data");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("DbTradeEventId")
                        .HasName("pk_trade_events");

                    b.ToTable("trade_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
